### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Nbesedin** [bitcoin-dot-org/bitcoin.org#1777] opened 2017-08-31 14:49 UTC
- date: 2017-11-15 - 2017-11-16 
      title: "Blockchain & Bitcoin Conference Moscow"
      venue: "СEC Sokolniki"
      address: "5-yi Luchevoy prosek 7/1
      city: "Moscow"
      country: "Russia"
      link: "https://goo.gl/7KPj3w"

**Comment by wbnns** [comment] 2017-09-10 14:47
@Nbesedin Thanks - I'm closing this since it is a duplicate of #1776.

**Closed by wbnns** 2017-09-10 14:47 UTC
Labels: Events
