### ISSUE TITLE
The DC Finance Family Office & UHNWI Conference: Investments into Blockchain Technologies & Cryptocurrencies

### ISSUE THREAD

**Issue by DCFinance** [bitcoin-dot-org/bitcoin.org#2082] opened 2018-01-18 12:19 UTC
The New York City High Tech Family Office Meetings are a series of select Semi Annual events dedicated to investments of high net worth individuals and single family office executives in high tech opportunities. Our next meeting is the first family office conference dedicated to the world of Cryptocurrencies. 

The meeting will explore the following – the future of cryptocurrencies (Bitcoin, Ethereum, Ripple etc.), the growing number of Blockchain based technology companies (media, gaming, fintech, AI, P2P, clean-tech, marketplaces, hardware, base protocols, security, social and more) and will answer different questions like what is an ICO; how does it work, the future of ICOs; Where the opportunities lie and what should be avoided; exploring the sharing Economy concept, How do the regulators, lawmakers, tax authorities view and approach the space and on the other end what is the advisers' point of view - legal and accounting issues (evaluation, bookkeeping etc.) and more.

We will map and explain the world of Blockchain and Cryptocurrencies by also looking at different point of views of various experts - from the leading investors in the field - VCs, family offices and individuals, to the field's top experts - academia, entrepreneurs, legal advisers and CPAs.

The conference will be followed by a cocktail reception and private investors' dinners throughout the week.

The conference will take place on the 25th April 2018, at Reed Smith LLP, New York

For additional Information please contact: aran@dc-finance.com

**Comment by wbnns** [comment] 2018-02-03 13:02
Duplicate of #2083

**Closed by wbnns** 2018-02-03 13:02 UTC
Labels: Events
