### ISSUE TITLE
World Satoshi Summit

### ISSUE THREAD

**Issue by wss1729** [bitcoin-dot-org/bitcoin.org#2210] opened 2018-03-13 11:01 UTC
12th-13th May 2018    
   
      venue: "JW Marriott"
      address: "Aerocity,New Delhi,India "
      city: "Delhi"
      country: "India"
      link: "https://worldsatoshisummit.com/
![700x700 2](https://user-images.githubusercontent.com/36760780/37337968-00035556-26dc-11e8-9d00-d7b47af8b6cc.jpg)
"

**Comment by wbnns** [comment] 2018-04-06 19:09
Duplicate of #2170

**Closed by wbnns** 2018-04-06 19:09 UTC
Labels: Events
