### ISSUE TITLE
Delist NYA participants from bitcoin.org

### ISSUE THREAD

**Issue by 0X676f61776179** [bitcoin-dot-org/bitcoin.org#1753] opened 2017-08-18 10:41 UTC
Come November, the NYA/2X signers have decided to launch their own altcoin based off Bitcoin's transaction history. This altcoin will be in violation of Bitcoin's rules of consensus and its blocks will be rejected by the participants following the main chain. 

While forking is an inherent feature of cryptocurrencies and decidedly not a bug, it no longer makes sense for bitcoin.org to keep promoting software solutions that wrest unsuspecting users away from Bitcoin and plant an altcoin underneath them.

If users are allowed to be whisked from the main network en masse, it may result in mass confusion, loss of funds, negative media exposure, setbacks in adoption, and another multi-year bear market.

Additionally, colluding behind closed doors goes against the open nature of open source software, cryptographic money and transparent consensus-making.

In that light, software solutions by NYA signers should be preemptively be delisted until they individually re-clarify their respective positions and explicitly commit to a) staying in consensus, b) not fraudulently promoting altcoins under Bitcoin's name.

**Comment by kuzzmi** [comment] 2017-08-18 11:21
This again touches the topic of defining a strict criteria for wallets that can and can not be listed on bitcoin.org.

I agree with the fact, that listing wallets that might lead to damaging of bitcoin reputation is a terribly bad idea. However, we first need to come up with a checklist. And this might take time. Advantages though are huge: 
1. We don't do the same thing that we're against - no closed doors. Bitcoin.org will prove that changes can be done transparently even in such cases.
2. We minimize amount of bias when a wallet should/shouldn't be listed, so less issues in the future.

What can be done for the time being is to display a banner with risks involved in using specific wallets with links to the GitHub issues, where additional discussion can happen. This way we can display worries of the community, with no 100% guarantees, and the warning itself will prevent very new users from using this wallets.

_linking #1751_

**Comment by theymos** [comment] 2017-08-18 11:23
I seriously doubt that most of them will actually go along with their suicide pact. I'd rather wait a while and see how things develop.

**Comment by friendsofbitcoin** [comment] 2017-08-18 11:38
Segwit has yet to activate and more NYA supporters like ViaBTC may back out. Let us be firm and begin temporary warning users but allow some of them to come to their senses.

**Comment by sir-lebowski** [comment] 2017-08-18 12:56
Copay wallet is generic in the sense that it can connect to anyone's server, not just bitpay, and that server may be be running the newest Bitcoin Core+copay/bitpay wallet service server. By default it's usable and connects to Bitpay. This is configurable in a menu option. Copay's design that it should be allowed on the bitcoin.org website.

Copay about as neutral as a wallet can get without having to recompile to change the backend service.

**Comment by is55555** [comment] 2017-08-18 14:42
@sir-lebowski there is a separate issue for Copay.

**Comment by Cobra-Bitcoin** [comment] 2017-09-26 18:57
There is too much silence around this. I believe like the main economic actors involved in this NYA takeover attempt (Coinbase & Bitpay) are still very committed to going through with it. Nothing has changed in the last month.

For now, let's just remove any mention of Coinbase and Bitpay (and their associated products), and put out an alert telling users to BEWARE of Coinbase and Bitpay because they plan on switching over to something that we believe isn't actual Bitcoin. The alert can have instructions telling users how to get their BTC off these services and recommend alternative companies that are committed to using the real Bitcoin.

What do you guys think? It just seems strange for bitcoin.org to remain silent and continue to act normal, even though a lot of the big services we're directing our users too have stated that they'll switch to an alternative centralized currency developed by @jgarzik which isn't and will never be the true Bitcoin.

**Comment by bitcoiner** [comment] 2017-09-27 18:17
aside from being on the original agreement that some are already backing out of, coinbase hasn't confirmed that they intend to fork, switch to 2X and call it bitcoin

we should wait before assuming and announcing what their actions will be because they'll need to let their users know first since it could cause many of them to not be able to transact with other users

**Comment by Roy19833** [comment] 2017-09-27 19:53
Holland - Feyenoord 2018 vs

Verzonden vanuit Outlook
________________________________
Van: bitcoiner <notifications@github.com>
Verzonden: woensdag 27 september 2017 06:17:26
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: Re: [bitcoin-dot-org/bitcoin.org] Delist NYA participants from bitcoin.org (#1753)


aside from being on the original agreement that some are already backing out of, coinbase hasn't confirmed that they intend to fork, switch to 2X and call it bitcoin

we should wait before assuming and announcing what their actions will be because they'll need to let their users know first since it could cause many of them to not be able to transact with other users

**Closed** 2017-11-18 12:17 UTC
Labels: On Hold
