### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by harding** [bitcoin-dot-org/bitcoin.org#1059] opened 2015-09-13 15:13 UTC
@greenaddress and I am having problems downloading https://bitcoin.org/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-linux64.tar.gz

- @greenaddress is having problems particularly on Amazon AWS
- I'm having problems on my Linode
- I'm not having problems on my home Comcast connection

**Comment by greenaddress** [comment] 2015-09-13 15:15
I tried from three different locations:

Ireland, Italy and Canada and it's pretty much hit and miss from all these places. Sometimes it works fine for a few minutes then it break.

If I can do anything to help let me know (testing etc)

**Comment by saivann** [comment] 2015-09-13 23:58
Is that still a problem? I have tried with my local connection a few hours after you posted this message, and just now, without any issue. The DigitalOcean VM also doesn't seem to have any issue as I have not received any alert telling me binaries were removed or unsigned.

**Comment by harding** [comment] 2015-09-14 00:09
Not for me.  I just tried several times in a row on my VPS and didn't encounter any problems.

**Comment by greenaddress** [comment] 2015-09-14 01:55
I haven't tested in hours but it worked fine last time I tried. Not sure what the problem was but thank you for having a look.

**Comment by saivann** [comment] 2015-09-14 16:37
Mmh, we had an issue in the past where downloads were randomly slow. This issue is probably also due to some connectivity issue on Black Lotus side, which seems resolve. Thanks a lot for reporting this issue. I am closing it for now but if you can reproduce it again, please feel free to comment here or open another issue.

**Closed by saivann** 2015-09-14 16:37 UTC
