### ISSUE TITLE
Height and Depth 

### ISSUE THREAD

**Issue by debkundu** [bitcoin-dot-org/bitcoin.org#2201] opened 2018-03-07 13:37 UTC
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

Location: https://bitcoin.org/en/developer-guide#full-node
Thank you for the wonderful documentation on Bitcoin for developers. I want to make an observation on the ‘height and depth’ illustration.
In the section on ‘Full Node’ under ‘Operating Modes’,we discuss the height and depth. In the illustration, there are a total of 103 blocks. The example on ‘height’ starts with the genesis block at Block 0 and the height goes to block 102 (total 103 blocks). However, the ‘depth’ starts at Block 1 at the top so it should end with ‘Block 103’ as the genesis block. Instead the diagram shows ‘Block 101’ as the genesis block. If this understanding is correct, you may wish to correct the illustration since most of us consider this site as the authority on understanding Bitcoin. 
Best wishes.

**Comment by TheRec** [comment] 2018-06-10 00:01
This seems to be a duplicate of #2301 and I have submitted a PR for #2301.

**Comment by wbnns** [comment] 2018-10-07 10:45
> However, the `depth` starts at Block 1 at the top so it should end with `Block 103` as the genesis block.

Apologies, not seeing this in the graphic. The graphic associates a depth of 1 with block 102. If there was a depth of 0 then there would be no penetration into the first block.

If I'm mistaken, someone please correct me and we can reopen.

**Closed by wbnns** 2018-10-07 10:45 UTC
Labels: Bounty, Dev Docs
