### ISSUE TITLE
VI BITCONF

### ISSUE THREAD

**Issue by Mandygomes** [bitcoin-dot-org/bitcoin.org#2282] opened 2018-04-13 02:44 UTC
- date: 2018-05-05
      title: "VI BITCONF"
      venue: "São Paulo - Brazil"
      address: "World Trade Center"
      city: "São Paulo"
      country: "Brazil"
      link: "http://www.bitconf.com.br/"

**Comment by beyourseff** [comment] 2018-04-17 07:59
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: It seems to be the case (program not available)

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: It seems to be the case (program not available)

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: There's another stage which will have talks focused exclusively on altcoins and ICO's

**Notes:**Duplicate of #2281 

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Closed** 2018-05-04 00:29 UTC
Labels: Events
