### ISSUE TITLE
CryptoBlockCon

### ISSUE THREAD

**Issue by gcsmithv** [bitcoin-dot-org/bitcoin.org#2133] opened 2018-02-06 23:56 UTC
- date: 2018-04-04
      title: "CryptoBlockCon"
      venue: "Hudson Loft"
      address: "1200 S Hope St"
      city: "Los Angeles, CA 90015"
      country: "United States"
      link: "http://www.cryptoblockcon.com/"

**Comment by wbnns** [comment] 2018-02-16 00:31
Duplicate of #2108

**Closed by wbnns** 2018-02-16 00:31 UTC
Labels: Events
