### ISSUE TITLE
Blockchain & Cryptocurrency Conference in Tokyo 

### ISSUE THREAD

**Issue by aksakei** [bitcoin-dot-org/bitcoin.org#1854] opened 2017-10-13 13:41 UTC
- date: 2017-11-11
      title: "Blockchain & Cryptocurrency Conference in Tokyo "
      venue: "Grand Prince Hotel New Takanawa"
      address: "3 Chome-13-1 Takanawa, Minato, Tokyo 108-8612, Japan"
      city: "Tokyo"
      country: "Japan"
      link: "https://www.ico.blockchain-labo.jp/conference-jp"

**Comment by wbnns** [comment] 2017-10-15 15:06
@aksakei Closing this as it is a duplicate of #1849. Thanks for adding! We'll have this live, soon.

**Closed by wbnns** 2017-10-15 15:06 UTC
Labels: Events

**Comment by aksakei** [comment] 2017-10-16 12:13
Dear Will,

thank you so much!

Ak
