### ISSUE TITLE
transaction not completing

### ISSUE THREAD

**Issue by ipxtreme** [bitcoin-dot-org/bitcoin.org#956] opened 2015-07-10 14:16 UTC
I saw this notice and upgraded immediately to 10.2 windows wallet on 7/7. I did a transaction on 7/9/15 and it has 0 confirmations for 12 hours now. Why?

I have done other transactions before that time and after that time. They all have had successful confirmations.

Source File: _alerts/2015-07-04-spv-mining.md

**Comment by harding** [comment] 2015-07-10 15:57
@ipxtreme I'm sorry to hear about that.  Have you left your Bitcoin Core wallet open so that it can rebroadcast the transaction to new peers it encounters?

Note: I'm going to close this issue because it doesn't have to do with the alert.

**Closed by harding** 2015-07-10 15:57 UTC

**Comment by ipxtreme** [comment] 2015-07-10 16:11
an I tell if this was submitted on a different fork?

**Comment by harding** [comment] 2015-07-10 16:16
Transactions are submitted to the network; even if they're mined in a block that later becomes stale (orphaned), the transactions can still be included in a block on the current chain.  I suggest you just open your Bitcoin Core wallet to let it rebroadcast that transaction.  If you'd like, you can provide me with a txid (or the whole raw transaction) and I'll help rebroadcast it using my node.

**Comment by ipxtreme** [comment] 2015-07-10 17:45
thanks. 78e43516e8cacff78ec507abc1c1defc3e4118f765e6637e32574dc6305d4d20

**Comment by ipxtreme** [comment] 2015-07-10 17:48
Status: 0/unconfirmed
Date: 7/9/2015 19:58
To: 1F3ZJtLqRYkhaZgdXkBNZkpm2NhbpPVzFX
Debit: -0.16852058 BTC
Transaction fee: -0.00000855 BTC
Net amount: -0.16852913 BTC
Transaction ID: 78e43516e8cacff78ec507abc1c1defc3e4118f765e6637e32574dc6305d4d20-000

**Comment by ipxtreme** [comment] 2015-07-10 17:50
here is the blockchain.info link:
https://blockchain.info/tx/78e43516e8cacff78ec507abc1c1defc3e4118f765e6637e32574dc6305d4d20

**Comment by ipxtreme** [comment] 2015-07-10 17:56
@harding How do I rebroadcast it from a node? My brother can do it from his wallet too.

**Comment by harding** [comment] 2015-07-10 18:51
@ipxtreme my node received it, so it may have been well propagated.  However, it does pay very low fees (0.00002565 per Kb)---below the amount my node estimates will be confirmed in the next 25 blocks (0.00010346), so you're going to have to wait a while.

Your brother can help relay using Bitcoin Core by going to Help -> Debug -> Console and pasting in the following command:

    sendrawtransaction 01000000026eabb832f0bbca71c287441f74dcd4a592319dddd61d4a17e1caf763cd6778ff000000006a47304402206868fadf4079f90db2828d7851acb6368715832525e9cb83c740739eab65d21c02204452366b750c007906e322a3a93fcec5a52773bc056817d8b34c9c78b2e4f5e00121028cbb3bc87ed0fd09175a3e129beb8115a8e489070c29fd626964d3ac8ca82e06ffffffff53a3f4c713abb0883a4c32dbd035f69d4862517bdbcf9e1cab2f6538e2781b4b010000006b48304502210087717810c8de1d2e11d7431412ae56dcf0e34e202ef71ee3e28aea45ea76061702203184786d3431da20b180d937f26478f128e019ead576735257215bf85ef97765012102c15aecb3f5f40c8074d6f5bdf4c58b9b91c825678b73fd1707f2d0238daf2a70ffffffff023e8e4700000000001976a91406c89c76bfd40b830bb5fdfb2fde69ed0b7062d988ac5a240101000000001976a9149a0d90040eb04082e5366c78d97df408727c6c3388ac00000000

**Comment by ipxtreme** [comment] 2015-07-10 19:31
Thanks.


Sent from my awesome Android device

-------- Original message --------

**Comment by ipxtreme** [comment] 2015-07-11 22:21
Still 0 confirmations. do you think the 25 blocks have past yet?

**Comment by ipxtreme** [comment] 2015-07-12 04:45
@harding do you think the 25 blocks are done already or still need to be found? I still see 0 confirmations. What about you?

**Comment by harding** [comment] 2015-07-12 11:46
@ipxtreme it's confirmed now.

**Comment by ipxtreme** [comment] 2015-07-12 17:19
@harding thanks. I will include the fee from now on. is there a config in the wallet to auto include the fee for every transaction?

**Comment by harding** [comment] 2015-07-12 18:14
@ipxtreme in the GUI, the Send tab has a fee chooser on the bottom of the screen in Bitcoin Core 0.10 and 0.11.

**Comment by ipxtreme** [comment] 2015-07-12 18:54
@harding thanks.
