### ISSUE TITLE
The Bitcoin Reformation

### ISSUE THREAD

**Issue by Dries-H** [bitcoin-dot-org/bitcoin.org#3271] opened 2020-02-13 07:00 UTC
- date: 2020-04-25
      title: "The Bitcoin Reformation"
      venue: "Zuiderkroon"
      address: "Vlaamsekaai 81/83"
      city: "Antwerp"
      country: "Belgium"
      link: "https://pretix.eu/bitcoinreformation/tickets/c/KJqoPjKAP/
      Header img: '![TBR announcement](https://user-images.githubusercontent.com/61001753/74409362-d8293080-4e36-11ea-86cb-8e74d3e66a26.png)"
"

**Comment by wbnns** [comment] 2020-02-13 12:40
Duplicate of #3264.

**Closed** 2020-02-13 12:40 UTC
