### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by fintechworldforum** [bitcoin-dot-org/bitcoin.org#1798] opened 2017-09-12 12:32 UTC
- date: 2017-11-21
      title: "FinTech World Forum 2017"
      venue: "The Great Hall, Kensington Conference and Events Centre"
      address: "Hornton St, Kensington, London W8 7NX"
      city: "London"
      country: "UK"
      link: "http://fintechconferences.com"

**Comment by fintechworldforum** [comment] 2017-09-12 12:33
Event Submision

**Comment by wbnns** [comment] 2017-09-16 19:52
Closing, duplicate of #1797

**Closed by wbnns** 2017-09-16 19:52 UTC
Labels: Events
