### ISSUE TITLE
The Bitcoin Reformation

### ISSUE THREAD

**Issue by Jeans5** [bitcoin-dot-org/bitcoin.org#3265] opened 2020-02-07 15:04 UTC
- date: 2020-04-25/26
      title: The Bitcoin Reformation
      venue: Conference
      address: Vlaamsekaai 81/83
      city: Antwerp
      country: Belgium
      link: http://bit.ly/2Oz6G8k

**Comment by wbnns** [comment] 2020-02-07 15:38
Duplicate of #3264.

**Closed by wbnns** 2020-02-07 15:38 UTC
