### ISSUE TITLE
Incorrectly-listed S2X companies

### ISSUE THREAD

**Issue by theymos** [bitcoin-dot-org/bitcoin.org#1835] opened 2017-10-05 00:48 UTC
Bitcoin.org will (soon) have a list of companies that will default to S2X. If there is **solid info** indicating that a company is incorrectly on or off the list, post here.

**Comment by eumartinez20** [comment] 2017-10-06 10:34
Crypto Facilities may need to be removed from the list. 
Email seems to be from Timo, could be the co-founder.

https://uk.linkedin.com/in/timoschlaefer/en

https://www.reddit.com/r/Bitcoin/comments/740son/nya_signer_uk_company_crypto_facilities_pulls/?st=j8fr55w3&sh=83321dbe

**Comment by prusnak** [comment] 2017-10-06 10:38
@eumartinez20  They have not announced the withdrawal publicly, yet.

**Comment by AdvancedStyle** [comment] 2017-10-06 12:53
Please can you add us to the list of Segwit2X companies:
https://bx.in.th/ (Thailand)

We are already listed here: https://coin.dance/poli

**Comment by piotrnar** [comment] 2017-10-06 15:48
I really believe that at the end of the day it is the miners that control the protocol. It all comes down to security and I could explain it to you with a few very simple examples, but my understanding is that you don't want to hear about this.

Anyway, since it is quite possible that the miners will choose to upgrade the block size, starting from block #494784, I am going to modify the consensus part of my gocoin project to allow up to 2MB big blocks, starting from that block.
The node will choose as active whichever branch will have more proof-of-work, without discriminating any of the two "implementations".

Therefore please feel free to label me the enemy of bitcoin and include my project in your funny list.

https://github.com/piotrnar/gocoin

**Comment by seweso** [comment] 2017-10-06 16:22
Are only businesses allowed on your list? I guess a lot of people implicitly follow the longest chain, with most people using SPV wallets and all. I think we should add all those millions of users also on the list. That's only fair. 

Maybe also proof of not hodling significant Bitcoin Cash or other alt-coins. As they stand to gain a lot from S2X failing. Or maybe the whole minority veto's by sybill's like Theymos wasn't such a great idea. 

Thanks for the list!! That's for sure.

**Comment by kbenzle** [comment] 2017-10-06 17:06
Add me to the list too please. Also, Coinbase, Bitpay, Poloniex, Gemini,... You know, better just add the whole Bitcoin community to the list of "attackers".

**Comment by kryptan** [comment] 2017-10-06 17:12
@kbenzle Coinbase and Bitpay are already on the list. Can you please provide proof that Poloniex and Gemini support Segwit2x?

**Comment by zander** [comment] 2017-10-06 17:17
Its not a company, but Bitcoin Classic added re-org protection to only follow the SegWit2x chain. I would be happy if you can list me on your page.

Thank you!

**Comment by PiscisSwimeatus** [comment] 2017-10-06 17:30
/r/btc should be added as well since most of the pro 2x users seams to be there after getting banned from /r/bitcoin

**Comment by tmaddison** [comment] 2017-10-06 17:32
Can I be added to the list?

**Comment by achow101** [comment] 2017-10-06 17:34
Please stop trolling this thread. Individuals are not being listed. This list is only for companies and services who have stated support for or against Segwit2x.

**Comment by PiscisSwimeatus** [comment] 2017-10-06 17:38
Should we add a twitter poll to gauge if the nakamoto consensus agrees that individuals should be added?

**Comment by creativecuriosity** [comment] 2017-10-06 17:51
@PiscisSwimeatus,  
You seem to think this situation is some type of joke.  
People will lose extremely large amounts of money in this fork.  
Money that was intended to send their children to college, care for their parents, and other life changing purposes.  
This isn't a drill, and it isn't a joke.

**Comment by x-ETHeREAL-x** [comment] 2017-10-06 17:56
That seems highly unlikely and hyperbolic.  In reality, it is unlikely that a minority chain will survive without a POW algorithm change, like BCH EDA, or a difficulty change.  When one of those happens, its an altcoin on a different chain that the heaviest POW chain and so it's not bitcoin's problem.  Even if both chain persist, then personal responsibility demands people assume responsibility for their coins on either chain and prevent replay attacks. 

Even for those uninformed users that do make replayable transactions, as we saw from the ETH/ETC chain split (where replays were constant for weeks), the fallout is not an existential crisis.

**Comment by eumartinez20** [comment] 2017-10-06 18:05
It seems not even Segwit2X has an updated list of signatories as no response has been given to their last email.

It will probably be quite difficult to get an updated list here (not just because of trolling but because I would expect some companies may never get here if they dont even respond on the S2X mailing list, so it may be a good idea to publish as is and update if issues later?

https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-October/000321.html

**Comment by apezio** [comment] 2017-10-06 18:29
Please add: Fork Networking <www.forked.net>. We support Segwit2x.
https://twitter.com/ForkNetworking/status/916369565730316288

**Comment by Coinfucius** [comment] 2017-10-06 19:34
We would be happy to have our support for 2x displayed on your site. Please add Coinfucius ATM Operator to your list. Thanks!

Verification: https://twitter.com/CoinfuciusSay/status/916384742643322881

**Comment by oojr** [comment] 2017-10-06 19:36
close the issue @theymos, the jig is up, banning doesn't work on this site, I believe...

**Comment by nyaaB** [comment] 2017-10-06 19:51
@apezio, you can't say you support something and at the same time state that you are not supporting it. There is no Segwit2x without segwit. So stating that you support Segwit2x is wrong when you don't support that part of it.

@Coinfucius, you should then declare support FOR it and not simply post childish comments on twitter.

@oojr, spam like yours can still be removed.

**Comment by tenthirtyone** [comment] 2017-10-06 19:56
I support 2x & Bitcoin Cash. I would consider it a point of pride to be added to this list.

Cryptocurrency offers a means of escaping the type of coercion and shame culture we are seeing in this post - and that is common among fiat currencies and their regulators. I support the people who have the most invested having a greater say than those who do nothing but talk and throw tantrums.

**Comment by chrisrico** [comment] 2017-10-06 20:16
@theymos I would change the wording on point 1.

>The company will not under any circumstances list “Segwit2x” as “BTC” and/or “Bitcoin”.

While I reject 2x and believe that most feel the same, I do think that if a *vast* majority of the ecosystem were to call 2x chain "Bitcoin", then it would be correct. Just like how ETH hard forked but ETC took a new name. That is the *only* acceptable reason to list Segwit2x as BTC, but to demand that every company agree to *never* list it as such under any condition is unreasonable.

**Comment by snavsenv** [comment] 2017-10-06 20:40
what is the point of this?

**Comment by tyler-smith** [comment] 2017-10-06 20:53
> what is the point of this? it seems like it will just create more unneccary drama

Creating unnecessary drama _is_ the point. It's all they know how to do in the face of losing their own project.

**Comment by bitcoinstore** [comment] 2017-10-06 21:01
Bitcoin.com will proudly list S2X, and we will list it as the default version of Bitcoin and will use the ticker BTC.  (Along with 95% of the rest of the ecosystem)

**Comment by Cobra-Bitcoin** [comment] 2017-10-06 21:20
> and will use the ticker BTC. (Along with 95% of the rest of the ecosystem)

@bitcoinstore https://i.imgur.com/NVPeTRz.gif

**Comment by instagibbs** [comment] 2017-10-06 21:21
@bitcoinstore that's going to really confuse your users when "BTC" suddenly loses 80% of its value

**Comment by Seccour** [comment] 2017-10-06 21:28
@bitcoinstore If you're going to use the ticker BTC for B2X... What are you going to do with your lovely altcoin Bitcoin Cash (BCash :*) ?

**Comment by JaredR26** [comment] 2017-10-06 21:32
I think you may have to add blockchain.info and BitGo to your list of "enemies of Bitcoin."  Both have CEO's in support if not fully committed on paper.  And for that matter, add me too.  I'm going to need a lot more popcorn than I thought for this show.

**Comment by CodeStackDave** [comment] 2017-10-06 21:49
add me, bitcoinDave to the list

**Comment by theymos** [comment] 2017-10-06 21:53
This issue is getting raided, so I'll lock it temporarily. If you want to make a serious post, come back later.

**Comment by Cobra-Bitcoin** [comment] 2017-10-07 11:21
Coinbase put out a [statement](https://blog.coinbase.com/update-on-the-bitcoin-segwit2x-hard-fork-69426f14bc85) saying they'll support both blockchains. Their statement isn't really helpful though since they don't specify how they will name these chains. Coinbase must immediately clarify that they will continue to call the current Bitcoin blockchain "Bitcoin" with the ticker symbol "BTC". It's absolutely unacceptable to rename people's BTC to something else, because this is likely to confuse them and lead to loss of funds. The fact that Coinbase haven't even figured out how to name these chains is concerning.

@barmstrong If you intend to call the Segwit2x chain "BTC", then please tell us now. The community needs to know as soon as possible so we can warn users to not naively sell their actual Bitcoin, and so we can explain to them what you have done to their money.

**Comment by seweso** [comment] 2017-10-08 09:14
The fair way to solve this whole debacle is have Exchanges 1) Continue to list Bitcoin as the combined token, thus if you deposit coins which are replayed you get Bitcoin (replay is a feature in this case). 2) Offer the ability to split Bitcoin's into BT1 and BT2, and allow trade. 3) Be super clear what will happen if you withdraw "Bitcoin" vs. "BT1" vs "BT2". 

Only if there is a clear "winner" can BT1 or BT2 be regarded as "Bitcoin".

**Comment by ojanssens** [comment] 2017-10-08 15:11
You list the chain with the most proof of work as Bitcoin, it's not rocket science, it's in the whitepaper. Knowing that 90%+ miners are going to support 2X, there's no reason to confuse customers. If Bitcoin Core and bitcoin.org would truly care that much about Bitcoin, they would accept defeat. If they want the 1MB chain to survive, I'd recommend to make haste in finding sufficient mining power or implement a POW change + add replay protection. Otherwise the minority chain will not stand a chance and it will be extremely detrimental and confusing for end users.

**Comment by chrisrico** [comment] 2017-10-08 15:17
@ojanssens Proof of work says nothing about which incompatible chain is Bitcoin, that is entirely a social question not an algorithmic one. Your backwards view leads to the eventuality that miners entirely dictate the rules of Bitcoin, which they clearly do not and should not.

**Comment by piotrnar** [comment] 2017-10-08 15:18
@ojanssens, exactly! 

What kind of "favour" is bitcoin.org website doing to these poor people, telling them that their bitcoins will be safer on the branch that has ten times less hashing power than the competing one?

**Comment by chrisrico** [comment] 2017-10-08 15:21
If a commitment to NYA ensure that the fork will have a majority of hash rate, why did Bitcoin Cash get up to 50% of hash rate when it was more profitable? *Clearly* miners will do whatever makes them the most profit, and salt futures markets are putting the price of Bitcoin higher than SegWit2x.

**Comment by ojanssens** [comment] 2017-10-08 15:24
@chrisrico If miners would do something completely unacceptable, pretty much everyone would reject it. A 2MB increase is wanted by many, and clearly not controversial enough for most companies and users in the ecosystem to reject it. In fact, most companies and users have been begging for this for years. The simple fact remains is that Blockstream and Core, together with their propaganda machines can just not accept the fact that they are in the minority. It is now their responsibility to accept proper defeat and move on, or they risk hurting Bitcoin tremendously and creating a huge amount of customer confusion.

**Comment by ojanssens** [comment] 2017-10-08 15:27
@chrisrico are you referring to this manipulated futures market? https://medium.com/@olivierjanss/why-bitfinexs-chain-split-tokens-are-completely-biased-towards-the-small-block-side-again-698395bae619

**Comment by chrisrico** [comment] 2017-10-08 15:30
What is your non-biased source of the claim that most of the Bitcoin ecosystem supports a SegWit2x takeover? Also, why do you even care now that you have your precious Bitcoin Cash? To me it just reads like you're trying to sabotage Bitcoin for the benefit of Bitcoin Cash.

**Comment by x-ETHeREAL-x** [comment] 2017-10-08 15:30
@chrisrico Mining profitability is not strictly a function of the current price, but of the expectation of the future price and the risk in getting there.  Miners cannot spend mined coins immediately, they must wait 100 blocks before they can spend mined coins. This introduces more into the calculus than the current price/current difficulty.  I don't think the fact that an instantaneously more profitable BCH chain lacks 100% of mining capability implies some benevolence in the miners who will save a minority 1x chain.

**Comment by chrisrico** [comment] 2017-10-08 15:36
@x-ETHeREAL-x That's not what I was getting at. The fact that miners abandoned Bitcoin to mine Bitcoin Cash after they had signed NYA is indicative that they will mine whatever coin is most profitable. They've *only* agreed to *launch* the fork, not exclusively mine it. People claiming that SegWit2x has a majority hashrate just don't understand how Bitcoin works at all.

**Comment by x-ETHeREAL-x** [comment] 2017-10-08 15:46
@chrisrico I understand that. But, I also understand Bitcoin is not designed to support minority chains.  The question is whether the initial hash rate switch will be enough to signal a winner quickly, rendering the minority chain all but stagnant.  Recall when ETH forked, the original chain was essentially dead for a couple of days, then when Polo listed the coin, miners instantly flocked to it and gave it new profitable life as ETC.  That probably won't work for bitcoin (by design) because the difficulty will not adjust without significant time/hash power.  Bitcoin needs hash power before it can even have transactions and possibly be useful/valuable. 

While you're right that miners can switch to a more profitable chain, what are the prospects of a minority bitcoin chain being more profitable (or even usable) after an initial massive switch?

**Comment by chrisrico** [comment] 2017-10-08 15:52
Your mistake is assuming that just because miners put "NYA" in their coinbase that means they will mine SegWit2x.

**Comment by x-ETHeREAL-x** [comment] 2017-10-08 16:05
It certainly is not binding, but what incentive do they have to false signal? Miners have the most capital invested as compared to most actors, they are heavily incentivized to do what will make the price the highest. I don't see how false signaling helps them, it would just introduce massive uncertainty and market instability for them to switch last minute.  It's not really that I trust them to do what they signal, but I don't see the incentive for them to false signal.  

That said, I do see incentives for them to force 2x. Many supporters of 1x (and the UASF) have suggested that miners are the enemy and there have been numerous articles about how miners don't really control bitcoin. I don't see the incentive for them to back 1x and prove right those who say they are the enemy/powerless. From their perspective, "bitcoin" will go on after they assert their power and force the fork, and they likely (correctly) believe that if they do, users will buy their coins (because there won't be any more 1x chain).  Interesting times we live in, it'll be interesting to watch.

**Comment by Seccour** [comment] 2017-10-08 22:25
@ojanssens - "Simply list the chain with the most proof of work as Bitcoin, it's not rocket science, it's in the whitepaper. "

Sure. So if an attacker with more hashing power fork off then his chain automatically become Bitcoin right ?

"I'd recommend to make haste in finding sufficient mining power or implement a POW change + add replay protection" - You are forking off. Which is something we didn't ask for. So if you care that much about users you should by default add replay protection. There is no reason for the people that doesn't want the change to add replay protection to their chain and legitimate the fork. And then regarding the PoW change i will not even let that happen even in your dream and you know why ? Because it will just mean that we will give as being Bitcoin and let you be it.

"something which is already clearly decided." - Sure. It's not what i'm seeing everyday when talking to users.

"A 2MB increase is wanted by many, and clearly not controversial enough for most companies and users in the ecosystem to reject it." - Numbers ? Figures ? Anything that would prove that most companies and users in the ecosystem don't reject it. For the number of companies if i take coin.dance as a source, more companies are against it that in favor. (And no being prepared for it isn't an endorsement) Regarding the users there is no figures. And taking the number of users companies that support 2x have doesn't reflect the reality of it since nobody did ask them.

"In fact, most companies and users have been begging for this for years." - So why not everyone did follow Bitcoin Cash then ? Why you didn't all fork off way before we did got SW if it's the case. Like if we're reading you, most companies, most users and pretty much the largest of the community in general love your plan and want to follow it. So why it wasn't done before ? Why did we waste 8+ months before  SW got activated ? While you were just able to fork off with the majority and have bigger blocks on Bitcoin.

"It is now their responsibility to accept proper defeat and move on, or they risk hurting Bitcoin tremendously and creating a huge amount of customer confusion." - You did try XT... Didn't work. You did try Classic... Didn't work. You did try Unlimited... Didn't work. You did try Bitcoin Cash... Didn't work. And you're going to try B2X and it will not work. You should read your own advice and use them. Move on.

So as you can see... If we really were the minority here, you would have won already.

**Comment by seweso** [comment] 2017-10-09 14:10
@Seccour 

>  So if an attacker with more hashing power fork off then his chain automatically become Bitcoin right ?

No, not immediately. Just like a few orphaned blocks are not Bitcoin. In reality what Bitcoin is will be determined by popular opinion, and that will most likely follow the longest chain of work. So it could take some time before it is clear which is which (probably within a few hours, but could take a few days). 

> You are forking off. Which is something we didn't ask for.

And we didn't ask for the blocksize-limit to be kept. If you are in the shitter doing nothing doesn't keep your hands clean. Let's agree to disagree on this one. 

> For the number of companies if i take coin.dance as a source, more companies are against it that in favor.

Are you actually just counting businesses? You think they all have an equal vote? 

Coin.dance own weighting puts it at 97% for SW2X.

>  So why not everyone did follow Bitcoin Cash then ?

NYA predates Bitcoin Cash. Weird question Seccour. 

> Why you didn't all fork off way before we did got SW if it's the case.

Bitcoin Classic was underhandedly destroyed through the HK agreement. Furthermore the NYA agreement was designed to have as little disruption as possible. Activating SegWit first made sense in that regard. Even activating it before UASF made sense (although I think letting UASF face-plant was better). 

> Why did we waste 8+ months before SW got activated ? 

Again, that would be the HK agreement. Which states SW + HF. No HF means no SW. 

You seem to be surprised by people holding unto agreements. 

> And you're going to try B2X and it will not work. You should read your own advice and use them. Move on.

Usurping the status quo is not akin to winning. The HK agreement was a disgrace, if that's what you need to win. As are all the censorship/attacks/propaganda/politics. 

There has not been an honest vote until now. Core didn't win, and XT/Classic didn't lose in a fair fight. 

Now Core has 97% of businesses 95% of miners against it. And you keep talking about you not being a minority? It would be funny if it weren't so sad. 

You do sybills, go promote exchanges like Bitfinex, go hold twitter polls. Let us vote with the best tool Satoshi gave us: miners & the free market.

**Comment by Seccour** [comment] 2017-10-09 20:34
> In reality what Bitcoin is will be determined by popular opinion

Thank you. Popular opinion doesn't seem to go in your direction so you can have as much hash power as you want.

> And we didn't ask for the blocksize-limit to be kept.

So fork off in a clean way instead of putting people's money at risk with such an unclean HF.

> Coin.dance own weighting puts it at 97% for SW2X.

I will not took it into consideration as long as i don't know how they proceed to calculate it. And it's 30% not 97%.

> You seem to be surprised by people holding unto agreements.

We don't need those agreements in the first place. If you want agreements between CEOs to be signed behind close door for Bitcoin, you did choose the wrong project.

> As are all the censorship/attacks/propaganda/politics

It come from both side.

> There has not been an honest vote until now. Core didn't win, and XT/Classic didn't lose in a fair fight.

There is no fair fight. Do you think it's fair for us to have to fight against a bunch of CEOs that own big companies and a few miners that would mine anything that could make them money even if it harm Bitcoin (Hi to all miners that did play with Bitcoin Cash EDA)

Oh they were fair. Nothing were blocking miners and companies to adopt either XT / Classic or Unlimited if they wanted to.

> Now Core has 97% of businesses 95% of miners against it. And you keep talking about you not being a minority? It would be funny if it weren't so sad.

What about users ? Just forget them ? And no it's not 97% of businesses.

> Let us vote with the best tool Satoshi gave us: miners & the free market.

Glad that you cite the free market. Because as you can see on Bitfinex, this attack is loosing. And don't say the same thing as ojanssens that Bitfinex way of doing thing is unfair and that's why it's not representative because it's not unfair. You have 95% of the miners and a majority of the businesses if we're listening to you guys. So there is no reason for you to not buy those tokens in your positions.

If you believe that much in what you are saying, not buying those BT2 tokens is first, irrational, and secondly it will be the biggest mistake of your life if you're right.

So continue to make fun of our Twitter polls, NO2X stickers, and everything. But that will not change the fact that in the end, Bitcoin will survive this, what i consider to be, an attack.

@seweso

**Comment by luke-jr** [comment] 2017-10-09 21:43
Mike Belshe (CEO BitGo) was today peddling dishonest 2X propaganda: https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-October/000369.html

**Comment by x-ETHeREAL-x** [comment] 2017-10-09 22:04
@luke-jr I really don't understand why you're against 2x as a technical matter? You signed the HK agreement, which contemplated a 2x hard fork with a 5 month projected gap in 2016. So it doesn't seem like that aspect is inherently unsound.  I understand the fight to maintain the reference client control, but if core just merged 2x, there would be instant consensus, no one would use BTC1 and core would retain the reference client. The messaging could be easily controlled to prevent block-back about giving in or anything else. Playing chicken with this winner-take-all 1x vs 2x fork seems non-ideal for all involved.

**Comment by luke-jr** [comment] 2017-10-09 22:09
@x-ETHeREAL-x For most answers, see [this reddit comment](https://www.reddit.com/r/Bitcoin/comments/61yvvv/request_to_core_devs_please_explain_your_vision/dficjhj/). Note that HKA was only to develop a recommendation for a 2 MB hardfork, not an 8 MB altcoin (which is what 2X is). Even 1 MB blocks are demonstrably harmful to Bitcoin; 8 MB is just outright insane.

**Comment by x-ETHeREAL-x** [comment] 2017-10-09 22:19
@luke-jr Can you point me to calculations that give 8mb, even in theory? That's not in your comment, and I would agree 8mb could present problems.  That said, I remember there was a single block on the segwit testnet that did 1.7mb filled with 1->1 p2pkh  transactions, and I remember hearing theories for how it could get up to 2.1mb, but I don't think anyone ever got that to work in practice.  The HKA said "an increase in the non-witness data to be around 2 MB, with the total size no more than 4 MB" which is what BTC1's implementation sounds like.  What am I missing?

**Comment by achow101** [comment] 2017-10-09 22:58
@x-ETHeREAL-x The base block size is [2 million bytes (2 * 1000 * 1000)](https://github.com/btc1/bitcoin/blob/segwit2x/src/consensus/consensus.h#L21). The maximum block weight is then defined as [4 times that](https://github.com/btc1/bitcoin/blob/segwit2x/src/consensus/consensus.h#L52), so it is 8 million weight units. The weight is defined in [BIP 141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#block-size) as block base size * 3 + total size in bytes of a block (witnesses are considered part of a block). 

Lets assume that we have two transactions in a block, the coinbase transaction and a very large one input transaction which spends a native P2WSH output, creates a P2PKH output, and has a very large witness. The block header is 80 bytes and the coinbase transaction of 251 bytes (average of the last 20 blocks' coinbase transactions rounded up). The non-witness size of the other transaction is 81 bytes.

We can now solve for the largest size in bytes for the witness. Let `X` be the size in bytes of the witness. Our equation is 
```
3(80+251+81) + (X+80+251+81)=8000000
1236 + X + 412 = 8000000
1648 + X = 8000000
X = 7998352
```
Therefore the largest size the witness of this transaction ca be is 7998352 bytes. Thus the total largest theoretical block size is `7998352 + 412 = 7998764 bytes`. This is ~8 MB. It can be even larger if the coinbase and the non-witness part of the large transaction were smaller (which is entirely possible, just not secure).

**Comment by x-ETHeREAL-x** [comment] 2017-10-09 23:51
@achow101 I see, thanks. Isn't the P2WSH `witnessScript` limited to 10,000 bytes? The BIP141 spec. seems to indicate that unless I'm misunderstanding.  In any event, I can see how you could get use 10,000 byte witnessscripts and get to be in the ballpark of 8mb.

**Comment by CosmicHemorroid** [comment] 2017-10-10 00:35
@x-ETHeREAL-x If messaging could be controlled S2X wouldn't be up the creek......

**Comment by rock217** [comment] 2017-10-10 11:33
>  Even 1 MB blocks are demonstrably harmful to Bitcoin;

@luke-jr where is this demonstration you allude to?

**Comment by luke-jr** [comment] 2017-10-10 11:56
@rock217 The current state of the Bitcoin network today. I go over this [on the linked reddit comment](https://www.reddit.com/r/Bitcoin/comments/61yvvv/request_to_core_devs_please_explain_your_vision/dficjhj/)...

**Comment by sturles** [comment] 2017-10-10 14:32
@ojanssens You suggest changing the names of coins every time the accumulated difficulty of one coin overcomes another.  Don't you think that will lead to some confusion when coins and tickers switch names on a block to block basis whenever one fork overtake another, and how do you think wallets, exchanges and merchants should coordinate the switches?  Does btc1 plan to implement dynamic name switching like you suggest?  How should we compare against forks with a different POW algorithm, like "Bittcoin Gold"?  Would you care to write a BIP on this subject?

**Comment by x-ETHeREAL-x** [comment] 2017-10-10 17:18
@sturles Such a strawman. There won't be two competing forks switching back and forth.  And, yes, when there's a hard fork, the chain with the superior POW/hashing power retains the name -- this isn't new or interesting, or surprising.  Obviously bitcoin gold is a POW algorithm change, and so is not in the same ballpark.  As between core and segwit2x, as a POW imbalance occurs, it will become exponentially less likely for a reversal to occur (just like if a chain re-org were to happen today and wipe existing blocks, no one would complain it wasn't "bitcoin").  Anyone who thinks there will be a 1x "core" chain and a 2x "segwit2x" chain after the fork is deluding themselves.  Bitcoin's difficulty adjustment scheme was not designed to allow a minority chain to survive, but rather to reach consensus on one "correct" chain, and without a difficulty change or POW algorithm change, one won't survive.  Right now, there is uncertainty about which chain will survive with both sides believing they will be victorious and pointing to alleged evidence that the economic majority supports their side -- we don't know who is right, but one or the other will be, not both.

**Comment by theymos** [comment] 2017-10-10 19:37
SurBTC posted an announcement which seems sufficient: https://blog.surbtc.com/our-stance-on-the-segwit2x-hard-fork-9fd04323667b

**Comment by sturles** [comment] 2017-10-10 19:59
@x-ETHeREAL-x  I admire your strong belief, but I am not convinced by your ability to see the future.  I have no idea how the future will play out.  Still, a policy will be required for this and any future contentious hard forks.

As long as I have been an active member of the Bitcoin community, since August 2010, there have been no precedence of contentious hard forks taking over the Bitcoin name by hashrate majority.  I remember hanging around in #bitcoin-dev in March 2013 when Bitcoin hard forked by accident.  Instead of splitting in two, and handing the name "Bitcoin" to the majority hashpower, people rushed to gain a hashing majority for the other side, killing the hard fork.  This hard fork had no wipeout protection, as opposed to the S2X hard fork, and was overtaken by the original chain.  You can read the full post mortem here: https://github.com/bitcoin/bips/blob/master/bip-0050.mediawiki

This is the only precedence I know about.  So far no altcoin other than "Bitcoin Cash" has been trying to nick the Bitcoin name, but BCH did not gain a majority of the hashrate.  Some BCH "black knights" still try to claim the moral right to the name, however.

There is nothing in the Bitcoin design preventing a minority chain to survive.  Almost all altcoins are based on Bitcoin, and several of them use the same POW algorithm as Bitcoin or other altcoins.

There will of course be two (or more) chains, since S2X added wipeout protection.   They added wipeout protection, because they don't expect to have a majority of the hashpower for long.  It is very clear which side the economic majority is on.  Almost no bitcoin companies, except for miners, have signed the NYA, and in Europe there is only one exchange/broker left supporting it.  Safello accept SEK, and has a spread of 15%.  However, due to wipeout protection, there is no way S2X can disappear.  S2X may drop to a very low value after a while, and it will be take a while since it is hard to sell for most people, but some pools and some miners still promised to support it, and I believe some will continue to mine it anyway.  Some even mine BCH when it is unprofitable.  So what happens if S2X gains a majority of the hashrate for a short while, then get overtaken by BCH and BTC?  If we are going to switch names of the coins, there has to be a policy of when that name change should occur, and at which frequency.

**Comment by x-ETHeREAL-x** [comment] 2017-10-11 01:07
@sturles 

> There is nothing in the Bitcoin design preventing a minority chain to survive. Almost all altcoins are based on Bitcoin, and several of them use the same POW algorithm as Bitcoin or other altcoins.

I disagree. I'm not aware of any altcoin that forked BTC and survived without a POW algorithm change or a difficulty adjustment. Are you? The very fact that there has never been a precedent for a minority chain surviving without such forced alterations only makes me more confident we won't see one here.  The difficulty retargeting algorithm seems very much designed (whether intentionally or not, but it seems intentional) to incentivize only a single chain to survive.  The blocks on the minority chain will come too slowly, and the retargeting will take too long, while the market will very likely it very unprofitable as compared to the majority chain.  Luckily, we don't need to agree. Time will tell who's right on all scores soon enough.   

>It is very clear which side the economic majority is on.

I disagree. It is very unclear. Both sides can marshal evidence, as you've done, to support their position that they control the economic majority.  Again, it really doesn't matter what you or I say, that's what' s great about bitcoin.  Nakamoto consensus and the market rules, not words, arguments, or supposition. Only time can tell who's right.  As I said above, I think this whole winner-take-all game of chicken is bad for all involved, but at this point it is what it is.  It seems unlikely core will merge 2x, and it seems equally unlikely the NYA group will abandon their fork.  So over the falls we'll go, and while messy, a chain will emerge as bitcoin and life will go on.

**Comment by sturles** [comment] 2017-10-11 06:33
@x-ETHeREAL-x Bitcoin does have a difficulty adjustment algorithm.  If the hashrate drops, the difficlty drops, and it becomes easier to mine BTC.  This has happened many times.  Your theory was tested in 2010, when someone mined with a lot of CPU power for a difficulty adjustment period, and then withdrew it, to prove that Bitcoin could be easily attacked by CPU power, and was doomed. Bitcoin survived.  Bitcoin doesn't know about the altcoins, so the situation is the same.  To bitcoin a lower hashrate is just a lower hashrate.

Bicoin is, and has always been one chain.  If people want chains to switch names based on most difficulty work, or some other metric, they need to formalize that process.  Otherwise they will create a lot of confusion among users who e.g. buy Bitcoin on Localbitcoins, and then try to spend their coins at some place which call S2X or BCH "Bitcoin".

**Comment by x-ETHeREAL-x** [comment] 2017-10-11 16:59
@sturles The segwit2x fork will occur at block 494,784. The first post-fork retargeting will occur at around 495,936, which is 1,152 blocks later and will include 42% of blocks mined at 10 avg of ~10 mins (it only moves as a weighted average of the times).  If, for example, one chain has only 10% of miners, blocks will come at average 100 minutes each (with lots of variance), and that 1,152 blocks will take 115,200 minutes or 80 days.  Even 20% would only half that to 50 minute blocks for 40 days.  Neither of these seem likely sustainable for that period of time given the massive losses any miner on that chain faces in comparison to the majority chain.  

What's worse, is that even after the retarget at 10%, you'd have 864 blocks at 10 minutes, so the difficulty would only get you 58% of the way to normal, which would make blocks roughly 42 minutes long, with the next retargeting about 60 days away.  Again, this additional 60 days would mean massive losses.  So, in total, to reach equilibrium, the minority chain is looking at  120 days -- 4 full months -- of massive losses for miners.  Not going to happen.  This is why a minority chain dies.

**Comment by piotrnar** [comment] 2017-10-11 18:01
IMHO, there is no question that if 90+% of the miners go into mining the S2X branch for more than a week, then the game is over for the hashing minority (let's call it S1X) branch. The majority of remaining <10% of the miners will eventually move to mining S2X before the fist re-targeting. And they will do it, simply because they will follow the value.
As the guy before me said: it is not a rocket science.

Also, from what I have seen, there is absolutely no objective reason to claim that most of "the users" support the S1X branch. Theymos and his camp have banned every opposition from expressing their opinions at the forums they control. Including mine. This basically leaves zero credibility for public opinions raised through these websites.

Moreover, if we get to the point mentioned at the beginning, whoever will be left believing in (betting their coins on) S1X branch, will only make us (people believing it's the hash power that sets the rules) richer. And that's despite of us trying to warn them to not bet on the wrong horse. Just like we once tried to warn people about the GLBS2 scam, paradoxically having the same people censoring our opinions at the forums they control :)

You guys should just chill the fuck out. Each one of you owns hundreds or thousands of bitcoins and you have absolutely no reasons to scam the poor people into buying your crazy religion. 

Sorry that this hasn't been very technical, but I hope you understand that anything that is left in this topic is strictly political. The fact that bitcoin core does not want to go for the 2X hard fork has practically zero to do with technical and  all to do with political - aka "we are in charge of the protocol".
Well, sorry mates, but you aren't in charge. Not because I said so, but because bitcoin is what it is and none of us can do anything about it.

**Comment by clarkmoody** [comment] 2017-10-11 18:33
> they will follow the value

Your are making a critical assumption: that 90% of hash power will lead to S2X being more valuable.

Let's look at the Bitcoin Cash mining situation. As it stands now, mining power rushes to Cash whenever it becomes more profitable to mine than Bitcoin. Can we expect the situation to be the same for S2X?

If yes, then we will need to see how the exchange rate of each coin evolves to know where the hash power will go.

If no, how committed are the miners to S2X? If S2X value plummets, will they mine at a loss until they kill the Bitcoin chain, no matter what? How much money have they committed to spend in this effort?

**Comment by piotrnar** [comment] 2017-10-11 18:40
> Your are making a critical assumption: that 90% of hash power will lead to S2X being more valuable.

I'm making an assumption that both will get a serious kick on their value.
But S1X will end up much worse, having like 2 hours to mine one block.

There is no practical reason to stick to S1X, if you have S2X mining block normally, with much lower fees, and having 10x more hashing power to secure the chain. Plus, just with 10% of it they can conduct 51% attack on your pitty little branch.
Do you really think that people are going to ignore all of these above facts and just stick to S1X because of some ideological reasons?
Well, if you do, then I can't understand why you got into bitcoin in the first place. :)

**Comment by clarkmoody** [comment] 2017-10-11 18:45
> I'm making an assumption that both will get a serious kick on their value.

That's all you needed to say.

**Comment by piotrnar** [comment] 2017-10-11 18:48
It's a gamble - we all know it. We know that the ones who can loose the most are the miners. And all the gambling is about it.
Still, is it worth it?

**Comment by flugkatze** [comment] 2017-10-12 01:07
If the chain still named Bitcoin, how it can happen to drop 90% of the ming power? I think 90% of mining pools can't stand for 90% of actual miners. It is likely to ask: "Whether it's the great brand of Bitcoin that support the mining industry or the mining industry support the Bitcoin brand?". I think at the time being the former is more likely. And the whole mining industry should think twice!

**Comment by sturles** [comment] 2017-10-12 07:00
@x-ETHeREAL-x I don't believe for a second that 90%, or even 50%, of the miners will switch to an altcoin which almost nobody will support for trading, and which currently trades for less than half the value of a bitcoin.  So far many pools have offered their miners to mine the new altcoin, but AFIK not a single pool said S2X would be their only option.  Hashrate is only speculation at this time.

10% on BTC would be plenty to keep the chain going.  BTC has lost more than 50% of the hashrate to BCH on many occations, and it worked fine.  The time for a difficulty retarget is much smaller than you think.  Both due to the current hashrate growth (assuming a constant 10% percentage), and the fact that you won't be able to keep any large number of miners to mine a coin which is of less value and harder to sell for a long time.  While some pool owners support S2X for political reasons, the miners seek ROI and profit.

Anyhow, it seems the discussion on naming is over.  Nobody are trying to defend @ojanssens suggestion to switch names on coins based on accumulated difficulty.  I think keeping the current naming will work better.  Bitcoin will continue to be Bitcoin and BTC, and S2X needs a new name.

**Closed** 2017-11-18 12:16 UTC

**Comment by sushilraghav** [comment] 2017-12-14 03:37
@theymos @eumartinez20 @prusnak @AdvancedStyle @piotrnar  For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
