### ISSUE TITLE
List of contributors isn't being fetched properly

### ISSUE THREAD

**Issue by emilengler** [bitcoin-dot-org/bitcoin.org#3003] opened 2019-06-08 13:05 UTC
Hello, the list of contributors does not work.
For example, I did two PR which also got merged([here](https://github.com/bitcoin/bitcoin/pull/14914) and [here](https://github.com/bitcoin/bitcoin/pull/15061)).

I looked at `_plugins/contributors.rb` and I think the error is there.
The GitHub API only fetches 500 contributors.
To get all contributors you need to add `anon=true`
So it would probably work if you would change line 22 to
`https://api.github.com/repos/"+repo+"/contributors?page=#{page}&per_page=100&anon=true`

I've also tested it (only the api) and it fetches much more names including my one.
The code snippet is untested yet, otherwise I would create a PR.

**Comment by wbnns** [comment] 2019-06-08 21:26
@emilengler 

Hello, thanks for reporting the issue. We'll check into it and see about avoiding the truncation like you suggested.

**Comment by emilengler** [comment] 2019-06-08 23:00
@wbnns Thank you :-)

**Comment by wbnns** [comment] 2019-06-09 08:31
@emilengler 

You're welcome. Looking into this more closely, the issue is that the two PRs you mentioned were not made on this repository. They were made on another Bitcoin-related repository, for Bitcoin Core: https://github.com/bitcoin/bitcoin

The About page on bitcoin.org that you may have noted you weren't appearing on only shows contributors to this repository.

Hope that helps clarify the issue.

**Comment by emilengler** [comment] 2019-06-09 10:29
@wbnns Are you sure about this ?
I mean [this](https://bitcoin.org/en/development#bitcoin-core-contributors) page

**Comment by wbnns** [comment] 2019-06-09 13:22
@emilengler Apologies, I thought you were referring to the About page. I see the issue on the Core contributors page - thank you for the link.

**Comment by wbnns** [comment] 2019-06-11 11:55
@emilengler 

We checked into this in more detail and the `anon=true` parameter will not resolve the issue because the GitHub API will [only return the first 500 contributors](https://developer.github.com/v3/repos/#list-contributors) (ordered by number of commits) to a repository:

![image](https://user-images.githubusercontent.com/1130872/59268520-2e612680-8c4d-11e9-839e-4431a36866e5.png)

In addition, [it seems there are instances where the API returns less than 500](https://stackoverflow.com/questions/44347339/github-api-how-efficiently-get-the-total-contributors-amount-per-repository#comment91994270_44347632), even when there are more than that limit. We tested with the bitcoin/bitcoin repository and noted a similar result.

We recommend that if you would like to ensure your name isn't truncated, that you continue to contribute which will raise your overall commit count. In the interim, you may find that you see your contributions acknowledged in official release notes, like in [0.18.0](https://github.com/bitcoin/bitcoin/blob/24dfcf3a56f90b101bc208f48ccdb7813fa08b83/doc/release-notes/release-notes-0.18.0.md), for example..

Here:

![image](https://user-images.githubusercontent.com/1130872/59269913-6a49bb00-8c50-11e9-8931-0ae051121010.png)

And here:

![image](https://user-images.githubusercontent.com/1130872/59269940-7cc3f480-8c50-11e9-9488-22f344bdcf72.png)

**Closed by wbnns** 2019-06-11 11:55 UTC
Labels: Bug
