### ISSUE TITLE
Malta Blockchain Summit

### ISSUE THREAD

**Issue by Avorin** [bitcoin-dot-org/bitcoin.org#2232] opened 2018-03-26 11:38 UTC
- date: 2018-11-01
      title: "Malta Blockchain Summit"
      venue: "InterContinental"
      address: "St George`S Bay"
      city: "St Julian's"
      country: "Malta"
      link: "https://maltablockchainsummit.com/"

**Comment by beyourseff** [comment] 2018-04-04 18:11
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Not that I've seen, more 'crypto-assets'

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, multiple.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment] 2018-04-06 19:53
Duplicate of #2212 

@beyourseff This event has speakers from several Bitcoin-related companies and/or organizations.

**Closed by wbnns** 2018-04-06 19:53 UTC
Labels: Events
