### ISSUE TITLE
Blockchain & Bitcoin Conference Malta 

### ISSUE THREAD

**Issue by ElenSh** [bitcoin-dot-org/bitcoin.org#1831] opened 2017-10-04 06:55 UTC
7 december 2017
Blockchain & Bitcoin Conference Malta 
InterContinental Malta, St George`S Bay, St Julians
Malta
[Blockchain & Bitcoin Conference Malta ](https://goo.gl/5PVafv)
![800 600-map-malta -st-en](https://user-images.githubusercontent.com/32294946/31163232-2bccda74-a8ea-11e7-977a-ea2d69f1b118.jpg)

**Comment by wbnns** [comment] 2017-10-15 14:53
Closing; duplicate of #1812. This will be on the website, soon. 👍

**Closed by wbnns** 2017-10-15 14:53 UTC
Labels: Events
