### ISSUE TITLE
Warning - Bitcoin.org compromised

### ISSUE THREAD

**Issue by wbinns** [bitcoin-dot-org/bitcoin.org#3398] opened 2020-06-24 19:17 UTC
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hello,

My name is [Will Binns](https://github.com/wbnns). For several years, I've been responsible for maintaining this repository that powers bitcoin.org, the original website used by Satoshi Nakamoto to provide early releases of Bitcoin, and one of the most visited resources about it on the internet.

Bitcoin.org, where many people also download the latest version of Bitcoin Core software, is now in danger of becoming compromised, if it hasn't just happened. @Cobra-Bitcoin has removed my access and seized control of the site and accompanying code repositories. I do not believe Cobra is the sole and lawful owner, nor does he have any right to do these things without just cause.

Cobra has referenced recent messages I sent in regular conversation regarding my work and the management of bitcoin.org as reasons for my departure. This has been taken out of context in an attempt to manipulate public opinion and infringe upon my rights, along with the rights of others.  I believe he is looking to [illegally transfer ownership of the site](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3332) without due process, and this may only be the beginning.

I'm writing this message to request assistance setting up a legal fund and the help of experts, to help stop this. In the interim, the website's treasury will be placed under the control of a trusted third party. The funds are safe, the site is not.

Please email will.binns@protonmail.com if you would like to help.

Regards,
Will

In case this thread gets deleted, a copy of this message may be found [here](https://gist.github.com/wbnns/693bc8d0f0b3480686477b0014ab0eff).
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEc+YwWcDUXDEaEg2GMC6+rut0pAQFAl7zpdAACgkQMC6+rut0
pASGKg/+OvSzQ18xP6atSd6a5Z8Ymt02xHiQFa403M+jBSf4ks6R5LBcvazezp6J
Y2HEnyc+poxioNzyV0Qj3cNtRjobw0XkaE8dcoTwHQjviFaA+WSrX8TUG8sUG0wt
legpmQklB1Qq7RlrJQdXIYj/tUd3DdKxFtjpNXoEvsthYEFRr4ziQ6Cs1/Huv/Ym
JPBXfP9vh4fDfxGMub41RsEwo0DplMkfjkp9AnKxsGa9B6zlyzGn6OuUhp4Ofv/O
3MsPCNpnhAHFLMb1FJOBTv/k1fJnNaLJTIs2eC79V5l3xGc99PJS5vawYyjVVGwa
OoXFqHiSCKCaXi5Rqxi4ARgjTT0snZcBDV4FlDXBU//it8BI5Yi8Hddb0J5p6jXf
n7IKZZomjRSf8cW17U1Eni1o1h97jxsHEnQyHeVsoo7PHeQITY8gOPmazZ4i5lC8
+NTc4x57rO8RVYd1pm6EIrDFQ2YVAkxlu0hsQLF3MLJF5pJEsTJjUhbjCVge7oCV
faL6tFEcXoHz3L+um81SvViejoGKIkEpe+oXwOG01k5xN0iAiwXM5/330zJ1czSC
vt4vM7OvxQcrrdZ2hFhqfhLMlEPeO9+Tj+VXTHMxqULxyvLrsREwqhzeMBj0l4bd
6tWCGYUuXerer9ik/eMjNFAKtGLQrjEtvVprtc54Igj24NNC7h4=
=x2nR
-----END PGP SIGNATURE-----

**Comment by mateusnds** [comment] 2020-06-24 19:45
The Real Will Profile: https://github.com/wbnns

@wbnns

**Comment by Cobra-Bitcoin** [comment] 2020-06-24 19:57
I won't delete this, better for me to leave it up, for transparency.

It's ridiculous to say I'm "seizing" a site I have owned since long before you ever got involved. Will Binns at no point ever had access to the domain name, he was merely a contributor on Github. Various people can attest to this and it's on public record, anybody can go on historical archives and verify for themselves, the "about" page has listed the domain owners for many years: https://bitcoin.org/en/about-us. I have every right to remove your ability to modify bitcoin.org as and when I choose, especially when you begin to attempt to muddy the waters into the extent of your relationship with the site and try to sign deals with entities like Mozilla. No such rights of yours are being infringed because you never had any rights over bitcoin.org in the first place: your name was never on the who-is record, and my registrar no doubt has records to back this up along with the domain being in the same account for far longer than your involvement with the site began. It's no different to someone claiming they own Wikipedia just because they contributed some articles to it. Or a janitor saying he owns the building. Your lack of respect for property rights, and attempts to say I have "compromised" my own website are absurd and people will laugh at you, not help you. Everybody knows my history with the site, and knows the extent of the level of access you had.

What I think has happened here is that Will Binns had gotten word that I was considering transferring the domain to someone infinitely more trustworthy than him (a developer who has been involved in Bitcoin basically since the start, we all know this person), and is feeling hard done by, or somehow expected the domain to go to him and now is trying to overextend his claims on the site. I had already transferred bitcointalk.org to theymos, and was choosing a similarly high-trust candidate for bitcoin.org. I have resisted massive offers from various nefarious entities over my many years of control of bitcoin.org, and I doubt Will Binns would ever be trustworthy enough to do so, that's why I skipped over him and decided to go with the aforementioned developer. Who is this "trusted" third party you have handed over all of the site's money too? I think the people who have donated should at least know that. Get as many legal experts as you want, you will be laughed at and mocked, and either waste your own money or waste somebody else's. Maybe go set up a fund to claim ownership of McDonald's because you flipped some burgers as a kid once. The laws are extremely clear in this regard, my attorney literally laughed out loud when I called him up and told him about this.

You are trying to take advantage of the community's contempt of me to build some public support, but it won't work because Bitcoiners are not stupid. I will make sure somebody trusted, respected and with a long history in the community is in control of bitcoin.org, not someone like you who would probably sell out to Roger the first chance you get.

I'm requesting you send all the site's money to a Bitcoin Core developer of your choice, and allow them to use the money to fund their work, rather than hold on to it and try to use it as some leverage over me or the site.

**Comment by ncoelho** [comment] 2020-06-24 20:01
Wait, this is a fake account... why?

**Comment by Cobra-Bitcoin** [comment] 2020-06-24 20:02
@ncoelho He doesn't have access to this repository anymore on his actual account.

**Comment by mateusnds** [comment] 2020-06-24 20:04
> @ncoelho He doesn't have access to this repository anymore on his actual account.

ahhhhhhhhhhhhhh

**Comment by harding** [comment] 2020-06-24 21:02
@wbinns 

> Bitcoin.org, where many people also download the latest version of Bitcoin Core software, is now in danger of becoming compromised

Why do you say this?  @Cobra-Bitcoin has controlled the DNS at least since I became involved with the site in early 2014, which gives him the ability to redirect the domain to any server he wants.  Even without changing the DNS entry, he's had access to the site server since mid-2015 IIRC (certainly he had access in 2016).  He's been an owner of the GitHub repository since mid-2015.  Each of these alone has given him the ability to change the content at any time, yet I'm unaware of him ever changing site content in a way that could significantly harm visitors.

> I do not believe Cobra is the sole and lawful owner, nor does he have any right to do these things without just cause.

What makes you think @Cobra-Bitcoin isn't the lawful owner?

> the site is not [safe]

Grr.  I just [criticized](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3397#issuecomment-649047941) @Cobra-Bitcoin for what I thought was his unwarranted character assassination of you.  I stand by that but now, to be fair, I need to say that I think you claiming that the site is unsafe under Cøbra's control is you assassinating his character.  In a parallel to what I said in that other post, Cøbra and I haven't always gotten along, but he's had the ability to use this site for evil for at least six years (and probably longer)---and he hasn't. So I don't think his reaction to (what is now clear) you trying to obtain ownership of the site self warrants you claiming he's going to compromise the site.

(That said, as a general policy, everyone downloading Bitcoin Core from this site or any other site should always verify the PGP release signature.  That's not new.)

**Comment by gmaxwell** [comment] 2020-06-25 02:02
I'd like to echo @harding 's comments here.  This appears to be an entirely unnecessary escalation.

If it could ever be said that Cobra in any way took over the time that happened was years ago. Cobra's control in-fact of the domain has been unambiguous and undisputed for years (though sure, at times of dispute some people have wished that wasn't the case). Any outsider to this matter doesn't need to look any further than the linked discussion about Cobra's plans to step down or Theymos' thread recent on BCT about control of the domains to see that no one was disputing that Cobra in fact has control.

If it were the case that Cobra were to behave inappropriately, sell the site to scammers, etc. there would be an argument to be had about the appropriateness of those actions and Bitcoin.org's existence as a community resources.  But that isn't the case here.  Personal drama aside, Cobra has consistently acted as a trustworthy steward for many years when he could have easily done otherwise (even as sometimes his own personal wishes appeared to be at odds, he refrained from imposing them on the site).  The fact that there is currently an unfortunate falling out with Will doesn't change that-- just like disagreements between Harding and Cobra in the past didn't change that back when Harding was one of the sites most active contributors.

I hope everyone (and especially Will) will pause, take a breath, let emotions subside, and re-engage without hyperbolic (and, as of yet, unjustified) language like saying bitcoin.org is compromised.

**Comment by Cobra-Bitcoin** [comment] 2020-06-25 03:47
I wonder if he'll ever tell us who this "trusted third party" is he plans to have control over the donated bitcoins?

The whole thing is absurd and ridiculous when you really think about it. If it does go to court, we're going to have some epic lulz, and I'll happily watch him go broke paying lawyers to try to convince people he owns something he so blatantly doesn't.

**Comment by wbinns** [comment] 2020-06-25 09:26
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

There is a lot of incomplete information being referenced here and on #3397. In the beginning, my work on bitcoin.org was as a volunteer. That changed over time. At no point, however, have I ever made any kind of offer to others to sell any stake in the domain or rights to the site. I am making no attempts to scam anyone. I hope my track record in the community that others have mentioned, as well as in the history of this project and on others in the space, speaks for itself. It spans for many years.

To further dispel any concern regarding bitcoin.org's funds, I would like [Chaincode](https://chaincode.com/) or [Bitcoin Optech](https://bitcoinops.org/), or individual Core developers associated with those initiatives, to be the trusted third party and for the majority of the available balance to be transferred to them, the only remaining amount to be withheld to settle hosting, development work and other remaining fiat-based expenses related to the operation of the site to close out the month. I trust their decision on how to best distribute the funds, whether that be to a new address associated with the site or in some other way.

Moving forward, I do believe the site itself is at significant risk, and the past, present and future ownership should be put to question. But I do not have the funds nor the legal expertise to spearhead that kind of initiative.

Just like many say we are all Satoshi, one website should not define the space. Bitcoin.org is not Bitcoin, despite the fact that it is one of the most visited resources about it. These recent events I think underscore the need for us to work together as a community to build and provide a wider array of helpful information, products and services. This year, more than ever.

So let's keep building.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEc+YwWcDUXDEaEg2GMC6+rut0pAQFAl70bXQACgkQMC6+rut0
pAQrWRAAjYcw6yEkgvBGbtOeBPGVgF3OkQs2e8i5+xJyqvZf9foEL0P7lvKOltKi
arWDIxU488mbumKh13eWFB+ra9JwKE5GXLo5crzqQQHO9SjKididhvMJs/3BxKsh
WYbpZ+/jmqm4o/28Mw/gGD/INGqSPT4WTASfq/22W0Y64NZwzARTRkWa+ka2vZUp
x4dhz/QOuK1oDMKPwL2J2wJG+fchawT7LEkBkoC8qsrrA4nfW2QxpUOzX9nPz3fs
g30xtuU2cu42pThsQrPQQgrAXW849pWMAgfLziSF9jkcmdksBgyZp1cOXdD1XLyz
1xKM3+vbrY+EpLatebpoduF2y8B/M/aCndaMjSSTowKu8NG7Cuu0q4eo7klFB4HL
izre+ZhNaKUufbfyNa8bM71/nFbJB2KgW7jKsEVhd/Hx4KigN56U8HU7hxBDnmmH
dELem1lB+tc3z7gqiIAFGYk5ooWV6UgBA4XKwE1bNWPkEhFUDYwGBOTJQKB3HCGW
5A6FQNLcBEpdCe5fkD3LOef2w0XaMlSnH0kMK47wsd8nw7uzE8hXZz7kuhNIwk9P
wSSPVukjihZHMjiyA0tf9MpP0V7CXRNQlr7MudKTRVQ9BuDG80eAFV6wsGYi0tq3
eS8YjrS5zIEYK5c/LOuZdNlR/bmLF27FcIvzfjpnZuKMvRy0eIY=
=m7Eu
-----END PGP SIGNATURE-----

**Comment by matthewlilley** [comment] 2020-06-25 09:37
The fact is that @Cobra-Bitcoin is the owner of bitcoin.org, many in his shoes would've sold bitcoin.org to the highest bidder, and had a legal right to do that. Instead, he's held onto the domain and the site has remained true to the spirit of Bitcoin, unlike other owners of similar TLDs, which have purposely muddied the water in various, and quite destructive ways.

From my experience, even though I've not always agreed with him on certain things, I think he's shown good character, and as others have stated, he has acted as a trustworthy steward over the years.

**Comment by Cobra-Bitcoin** [comment] 2020-06-25 13:21
> In the beginning, my work on bitcoin.org was as a volunteer. That changed over time.

What on earth did it change into? Are you claiming it changed into ownership? You are being vague, not clear. I have never formed any LLC with you, nor given you any access to the domain, nor signed any contract with you regarding bitcoin.org's ownership. And once again, you don't even _know_ me; at most your access extended to merge access to a Github repository and some control of servers used on some less trafficked subdomains of the site. In fact, I had trusted other people with direct main server access and control over the DNS over the years, but never you, because I had a vague uncomfortable feeling about you.

> I trust their decision on how to best distribute the funds, whether that be to a new address associated with the site or in some other way.

They will ideally send it to the new donation address currently on the site, so I can actually pay the sites expenses. I doubt they will keep it hostage to help further your agenda, because basically nobody in the community agrees with you, I'll wait and see if you actually do send them any money, so far looking at the addresses, nothing has moved. I'll get concerned if that remains the case for much longer.

> Moving forward, I do believe the site itself is at significant risk, and the past, present and future ownership should be put to question. But I do not have the funds nor the legal expertise to spearhead that kind of initiative.

The site is not at any risk. The site is in the same hands it's been in for the majority of its existence. There is no amount of legal expertise you can muster to spearhead your proposed "initiative" because you have no actual claim or rights here. At most, you will find a lawyer who will just gladly take all your money and watch you lose.

> Just like many say we are all Satoshi, one website should not define the space. Bitcoin.org is not Bitcoin, despite the fact that it is one of the most visited resources about it. These recent events I think underscore the need for us to work together as a community to build and provide a wider array of helpful information, products and services. This year, more than ever.

Bitcoin.org obviously doesn't define Bitcoin, nor does it represent Bitcoin. To be honest, for the most part the site is quite irrelevant in the grand scheme of things: mostly noobs come, learn about Bitcoin, and then don't really visit again. But that's only so long as the site is in good hands, if the site ends up controlled by bad actors, it becomes a massive piece of propaganda, obviously it wouldn't destroy Bitcoin, but it would mean the _majority_ of people looking to learn about Bitcoin would get tricked by the first top two natural search results. I perceived your attempts to insinuate you had some ownership of the site as an attack, and had I allowed you to continue to be part of the project while you believed such nonsense, it may have caused me legal problems in the future. I'm sorry, but in business, as soon as you start saying things like "what's yours is mine", you are crossing a red line.

There are many good projects in the space which you can contribute too, and this will likely all be forgotten in a few weeks. But if you keep pressing these claims that your role in bitcoin.org was more than what it really was, you will be seen as a bad actor and less and less people will feel comfortable working with you. As someone who's been the recipient of community distrust because of my opinions on Bitcoin Cash, it's not fun having people's first perception of you be negative. For me it's much easier though, being behind a pseudonym, but you will find it more difficult.

I'm sorry if my actions seem harsh, but it had to be done. I appreciate all your contributions to the project, and I'm sure you will contribute good work to other projects. When you've sent the money as you have promised, please tell us who the recipient of the money is and the transaction id, for the sake of transparency.

**Comment by wbinns** [comment] 2020-06-25 15:14
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

This message is to confirm that the current balance of the treasury is 8.43576562 BTC.

The final amount transferred will be less, per the obligations already mentioned above, and also minus the return of 3 exchange review fees of approximately $2500 each for [exchanges reviews](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md) that were ongoing that will now be canceled and returned (fiat value of amount paid in BTC fluctates according to BTC/USD). Since my access has been removed, including access to will@bitcoin.org and exchanges@bitcoin.org email addresses (any emails sent from those addresses since yesterday are not from me), those reviews will need to begin anew with other points of contact for bitcoin.org, should the exchanges wish to proceed.

A statement of cash flows will be included with the transfer when the bitcoin address used to collect receipt has been agreed upon/finalized.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEc+YwWcDUXDEaEg2GMC6+rut0pAQFAl70vsoACgkQMC6+rut0
pAQwVQ/+MZG5bemXT6+jzjmaUlppJ/Y0v+giXWTywHAW9F4Fa2F3SLDwITgQC2N/
HiwX+bEE8dYf3P9BzKKDlu2LYqynSAoCNNaNB1AsOb7rqNZ/3Xv9b4t1U2+QSmfp
G45HHm5fc4SiMhJCvEmSMworhPafZ5J5Je7/4iwdm9R51I8v+eJwWLq5AU4adPYJ
M+n30q+F6gZciCr+ps9fi7hicwHVRC3n9Lnio1rcRtnDbHhAqwTSKP/7lmeuiT6I
wffp4CTbvEUy47XxqVY7PZ+BcEjAOsqt2mLiFjeG34ijz3QUU9jeMPjfzbjpAL5Y
aaL32HQFI35zTO9ng7xdsOWqKocY5goGPMQ6fZp4Flq3CLnaiPzcOlEK0rXPeVIZ
WmB10fq6VpB0ycJ81Wls4kTNbjyJKyA+pvKRRoLb54kS1XyRygJmP+TzwUZbzHt0
RHay7jwLsaG3z7az8W0Xjcx1LxD4ukijZqs2tK4mVcy0aDePhjwI338MO4PiUend
8sKa2vV3wziU1okMwIQKihUbGxuhBpWfB/g5BTxg/WBFXG6yEytgJsXOtSDkFu9F
vs/yOnJD7XFRHFEQk8IrYnzI7M7ggwQ+LvrQNA5h9NoTRBGxH3qMF4sTXGZ6Owuh
G3KI7xJW4KHrMVJGDsPm9ZrYLEauhtBG+vC+y59bf9xSIXbRvhs=
=V47o
-----END PGP SIGNATURE-----

**Comment by wbinns** [comment] 2020-06-25 19:23
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@Cobra-Bitcoin

Can you confirm if the bitcoin address you ideally would like the above funds sent to, is the same address  - 3NSG2UvEaoHUJZcd5nRXiFsq7EnSP93GCR - you've recently added to the site?

I haven't changed my stated beliefs, and there's a lot that hasn't been said, but I'm not interested in wasting time arguing on the internet or being dragged through the mud. I would rather leave this up to you and the community to sort out, and focus on other things.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEc+YwWcDUXDEaEg2GMC6+rut0pAQFAl70+SYACgkQMC6+rut0
pARacA/+Or81Vzii2kGAHTHL7mAp4rCcbzIsERKoTLm2PjhllsKjkqZwuV7JNPbN
Zz1lPSQyUAX1fLdanicmStAuT7zLNjEGiu5ybUb6mknd5Oora+2bLiNc+doFsUE1
/o4L4jSoXHH6ZCcIxl1QfW2uTqTaTtDjJAN6NpQZV2O99X9I2gVBgo9yWj0p3FKn
ZEH/ZGLg/Ij4eNM13zsLGuJyaDNKP4H6//xCXBI4gQ8N2F1LosT7AM5lh2WU3KzY
ygNP79mPIHuYtLrhjDMeOFWcCM1ad7+duShYslrwUIly3+LxYIEYJWeUSAYw0tQ7
LDY93iEdXCqRwmuMOOJS6P5+CKHUy7E0HeuXfYyurJGR465MvxLAFBaCJP4YHSm6
b3qFsMJSgdsBPgndD+bMXJxHERZIzkIucEJStAtTyy4aAA5IIHD+L99F8YDsIFXv
P3AEN0kakdV7aYYeVpT1XAL4bAic5qreG9wSpXdLFyg51qfVaXxzd14N7p5xUpNY
P3FjoBheMkCVO3N51otr8On8SMzvaFw7keJi7e4A/fa8halgfWe0pvL5m6nBtB4s
kFAeKTevrqJgi7KY3mvLpK/9kOkM1Fv7+U/JUfUI1B14EEc77cDyOM9HgvC3QkOl
b7cQu4dcHz2ez9axm5018O7Fcs+ehNbUZ9VOJidklOvCd5kczbE=
=LUBH
-----END PGP SIGNATURE-----

**Comment by Cobra-Bitcoin** [comment] 2020-06-25 19:48
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Yes, I can confirm 3NSG2UvEaoHUJZcd5nRXiFsq7EnSP93GCR is the new
wallet for the site's donations.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCAAdFiEEYVWbHu+z+NpsQLqsb4VZRHjOTHoFAl70/wUACgkQb4VZRHjO
THq9TwgAlF/z9a/k2JGHpfPLgsc0a1DcJLgfhVxRO8FOaUeJLPJUKZhnv9kqpXfV
lernmiLNOqil4J/kYSO13QSULlHWphAtBZffCamRS838C+eaCdaT3il9omBn4tMv
VE243XrZOsq1nXvxua1fHxaMECFnAfUaU6xb5ABRVD19bUxTB9LAA+XQdAoBTyYm
rPPXWuVMGicvV8dUVPzL6lXuCW+A1JZIXwoa0sugfd1luTebcOvVj2ZWgwrok6oo
wYjkXkCMOHND84w/lF4CdQSUsj8nZUAh1s/wPGgaxb9LgiXnubuAke8kDlMYueNp
md11Rgc27smD9PTTFCx6Uv5AOB++Mg==
=vX0t
-----END PGP SIGNATURE-----

**Comment by wbinns** [comment] 2020-06-25 21:01
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The majority of the treasury balance has been sent to 3NSG2UvEaoHUJZcd5nRXiFsq7EnSP93GCR ([txid](https://live.blockcypher.com/btc/tx/5510516694ed62368f7dff432e7f030b56e8fdd7ad4e00b52fc84ba8065fe5ba/)). I do not have access to these funds, so I can no longer vouch for their safekeeping, or how they will be used for the benefit of improving the site for the community and new users going forward.

The rest of the funds have been set aside as already mentioned above and the remaining balance will be sent along with the final statement of cash flows in early-mid July following the close of this month.

Thank you to everyone who has helped with the site and collaborated with me over the years on bitcoin.org.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEc+YwWcDUXDEaEg2GMC6+rut0pAQFAl71D8sACgkQMC6+rut0
pATNcg/+JVg061knLCd+GkgJj0o8q5RfAkrvNk8TCed9gVTveAEV9cEaAsovXqUA
HoQMb4nEnsHOzN3VNhyb3xmO82gmstwapUkY19OhMw+L48vbWbuLJRGI8n0odHum
+HpgdSm3fmYWa7AveIiDnLhynZCSmJ6WUl566LiXknbxJy5Moei4DVkm0ZGSqHyv
6oXgh/4RJKyeIRi409T1u7hvjdouix+e1CxJU+a+bph25y6VP8+SPmY6tFEKn2tx
z9/kgqeZKZw9AO7OD2q/WPCoBIC7Zz5Jz12IAKa+EBXsyiXx8+LftrYxIQf99RJ9
dkIZNPe2BLc1F+6DCsLNvN8IFQD1R21D1jRZ8u6MlDk/ss5aucZh5izb4FmBNSlP
XJDaL5Do+aTTetqYXTGQnWm2GJ/5GVDn6FlBXaFmstSjicRlU4WAyvEiPKCEvdUR
0FGwM5/e0Fsst0FAUxRUC6W+jU6NBgqv58SsX7DMhUbhAXjyv1vQxmpBZyLFiNXL
Y5yxIJtamZBK91LxjsNf2se78kdfPqGU+g6QzCrMtuFv1Iwb7eSLVS3gWbrwNJrJ
Yvp9xUP8VjhGNThg6NVT2B+UeCtRBh6lHdaupDwCV7inIFj/r8YJhwdWKAC0WH0m
FvKylUc2tTSusW9nF76m31D2vJp4bU1iSqlD6Gv/5Tdu73tsb1o=
=JCl7
-----END PGP SIGNATURE-----

**Comment by Cobra-Bitcoin** [comment] 2020-06-25 23:44
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Thank you, Will.

The money sent to 3NSG2UvEaoHUJZcd5nRXiFsq7EnSP93GCR will remain untouched for the time being.
I've updated the donation address to 3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd, this is where Will
can send any of the remaining balance.

For the foreseeable future, and until the donations accumulate again, I will pay all expenses
out of my own pocket. The sum in 3NSG2UvEaoHUJZcd5nRXiFsq7EnSP93GCR will only be called upon
in a legal emergency (should things start to go down that road). If after some time there
doesn't seem to be any legal situation, the money will stay as reserve and go towards the
usual site expenses.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCAAdFiEEYVWbHu+z+NpsQLqsb4VZRHjOTHoFAl71NkoACgkQb4VZRHjO
THqrDgf+OYH5OXDnxWC5PiDfdwwGm/QAbqAlE5zHjYgeNYa86mvii+v90d6ijJYD
F0KIIXewI4uiBHZ14EFPSLFxRFQSSSNGNgsEhfQZFnsn8GpmgLFYvY6TWMHOlnZn
bPK9SaBzYp3K5UNXEF1PE50OK91TI1eK+xvY/bSB0z5vbR9/w7LLxT3kBoDuGpxh
9zU8Y2HPILQ+SoNcTUCbpvju8yv3fL5W/vSZChqjuNDyrFZhOZdjDUkypgnuig5Q
EM3cFu74YEqz85jOV0hST3U9+GtexDs3Ky7LUEFinA54/qewHC0+P6JSSWx61Xb9
ORqqPDgGlwLaSVLfAvXxnO7l6Rdh2g==
=8QtQ
-----END PGP SIGNATURE-----

**Comment by Cobra-Bitcoin** [comment] 2020-06-25 23:44
Locking this now since this matter has concluded.

**Closed by Cobra-Bitcoin** 2020-06-25 23:44 UTC
