### ISSUE TITLE
Blockchain Economic Forum 2018

### ISSUE THREAD

**Issue by roma-latoken** [bitcoin-dot-org/bitcoin.org#2040] opened 2017-12-29 14:42 UTC
- date: 2018-02-04
      title: "Blockchain Economic Forum 2018"
      venue: "Suntec Singapore International Convention and Exhibition Centre"
      address: "1 Raffles Boulevard, Suntec City"
      city: "Singapore"
      country: "Singapore"
      link: "https://bef.latoken.com/"

**Comment by wbnns** [comment] 2018-02-03 12:34
Duplicate of #2040

**Closed** 2018-02-15 23:39 UTC
Labels: Events
