### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Xivw** [bitcoin-dot-org/bitcoin.org#3416] opened 2020-07-12 07:50 UTC
- date: 2020-07-14
      title: "Mining secrets 2020"
      venue: "-"
      address: "Online"
      city: "Online"
      country: "Online"
      link: "https://xiveacademy.com/"

**Comment by Daniel-Leedan** [comment] 2020-07-21 09:15
Duplicate of #3411

**Closed** 2020-08-20 23:41 UTC
