### ISSUE TITLE
$1.2M Traded on Quebex.com!

### ISSUE THREAD

**Issue by davidquebex** [bitcoin-dot-org/bitcoin.org#2968] opened 2019-05-11 12:10 UTC
Dear bitcoin community,

Quebex.com P2P exchange is now at $1.2M traded since 2016. Last trade was made by MarcosRodrigues for $3,000.

Are there any contributors that would like to add Quebex.com to bitcoin.org?

Benefits include:
* Instant verification (< 5 minutes)
* No Photo ID required
* No deposit fees
* No fees for trading CAD
* No CAD deposit withholding time

Quebex is a federally registered MSB with FINTRAC Registration #M17947675 and licensed with AMF #903510.

We offer email support, live chat and phone support at (888) 661-3358.

Accepted payment methods include: Email Money Transfers, Bank Deposits and PayPal.

**Comment by aaronkuchma** [comment] 2019-05-12 02:39
As a contributor (of this PR https://github.com/bitcoin-dot-org/bitcoin.org/pull/2977 ), I agree that Quebex is great and should be reviewed.

**Comment by achow101** [comment] 2019-05-12 04:40
Bitcoin.org's issues are not the place to advertise your service.

**Comment by davidquebex** [comment] 2019-05-12 16:54
Andrew, this is not advertisement. We are just  giving facts as to why Quebex.com should be recommended to the Canadian bitcoin community. Thanks! David

**Comment by wbnns** [comment] 2019-05-12 20:10
Duplicate of #2960.

@davidquebex @aaronkuchma Please stop spamming the repository. Other contributors and people following along can see all of your messages in issues and pull requests, regardless of if they are open or closed, and can make their own informed decisions and recommendations if they would like.

**Closed by wbnns** 2019-05-12 20:10 UTC

**Comment by davidquebex** [comment] 2019-05-12 20:19
Hi Will,

Ok sure. Was not aware of that.

I have a feeling you are the boss on bitcoin.org. :)

Why are you closing the issue? You didn’t even reply?

Now that you have seen all the scam and fraud complaints, will you be removing the scam sites?

Cheers!

David

**Comment by davidquebex** [comment] 2019-05-12 22:22
Well, at least you fixed the space in the documentation :)
