### ISSUE TITLE
Free Trading On KuCoin For Platform 2.0 Launch

### ISSUE THREAD

**Issue by KaraCryptonite** [bitcoin-dot-org/bitcoin.org#2862] opened 2019-02-19 09:07 UTC
Free Trading On KuCoin For Platform 2.0 Launch

In celebration of this special moment  for #KuCoinV2 Launch,  You can enjoy zero trading fees for all trading pairs, expiring at 23:59:59 Feb 21, 2019 (UTC+8).

See the event here: https://www.kucoin.com/activity/46

**Comment by wbnns** [comment] 2019-02-19 19:24
Closing, duplicate of #2854.

**Closed by wbnns** 2019-02-19 19:24 UTC
