### ISSUE TITLE
Blockchain & Bitcoin Conference Gibraltar

### ISSUE THREAD

**Issue by smileexpo1** [bitcoin-dot-org/bitcoin.org#2017] opened 2017-12-26 13:00 UTC
- date: 2018-02-08
      title: "Blockchain & Bitcoin Conference Gibraltar"
      venue: "Hotel Sunborn Gibraltar"
      address: "35 Ocean Village Promenade"
      city: "Gibraltar"
      country: "United Kingdom"
      link: "https://gibraltar.bc.events/"

**Comment by wbnns** [comment] 2017-12-27 14:40
Duplicate of #1966

**Closed by wbnns** 2017-12-27 14:40 UTC
Labels: Events
