### ISSUE TITLE
Congress #BlockchainRF by RACIB

### ISSUE THREAD

**Issue by EgorychevD** [bitcoin-dot-org/bitcoin.org#2142] opened 2018-02-09 10:15 UTC
20-21 February 2018
Industry congress of developers, blockchain technology users and products based on its basis, for the development of digital economy
Summing up 2017 and giving forecasts for 2018
Krasnopresnenskaya embankment., 12
Moscow
Russia
rc.moscow

**Comment by wbnns** [comment] 2018-02-16 00:21
Duplicate of #2129

**Closed by wbnns** 2018-02-16 00:21 UTC
Labels: Events
